WITH tree AS(
SELECT A.ITEM_ID, A.PARENT_ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE A LEFT JOIN ITEM_INFO B ON A.ITEM_ID = B.ITEM_ID)

SELECT B.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_INFO A LEFT JOIN tree B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE A.RARITY = 'RARE' AND B.ITEM_NAME IS NOT NULL
ORDER BY ITEM_ID DESC;