WITH over_3000 AS(
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    WHERE TOTAL_ORDER > 3000
)

SELECT A.FLAVOR
FROM over_3000 A LEFT JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;